/* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

import { defineConfig } from "@forsakringskassan/vite-lib-config/vite";
import { defineTestConfig } from "@forsakringskassan/vitest-config-jsdom";
import mocks from "./src/mocks.mts";

export default defineConfig({
    test: {
        ...defineTestConfig(),
        globalSetup: "./global-setup.ts",

        environmentOptions: {
            happyDOM: {
                url: "http://127.0.0.1:8080",
            },
        },
    },

    fk: {
        mocks,
    },
});
