/* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

import { defineConfig } from "@forsakringskassan/vite-lib-config/vite";
import { defineTestConfig } from "@forsakringskassan/vitest-config-jsdom";
import mocks from "./src/mocks.mts";

export default defineConfig({
    test: defineTestConfig({
        environment: "jsdom",
        environmentOptions: {
            jsdom: {
                url: "http://localhost:3000",
            },
        },
        setupFiles: ["./vitest.setup.ts"],
    }),
    fk: {
        mocks,
    },
});
